version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ${NC_PATH}:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    secrets:
      - nextcloud_admin_user
      - nextcloud_admin_password
      - postgres_db
      - postgres_password
      - postgres_user

  web:
    build: ./web
    restart: always
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ${NC_PATH}:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=shuta4.com
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ${NC_PATH}:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

#  proxy:
#    build: ./proxy
#    restart: always
#    ports:
#      - ${HTTP_PORT}:80
#      - ${HTTPS_PORT}:443
#    volumes:
#      - ${CERTS_PATH}:/etc/nginx/certs:ro
#      - vhost.d:/etc/nginx/vhost.d
#      - html:/usr/share/nginx/html
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#    networks:
#      - proxy-tier

  backups:
    image: ghcr.io/linuxserver/duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Moscow
    volumes:
      - ${BACKUP_CFG_PATH}:/config
      - ${BACKUP_DEST_PATH}:/backups
      - ${BACKUP_SRC_PATH_0}:/source/0
      - ${BACKUP_SRC_PATH_1}:/source/1
    ports:
      - ${BACKUP_PORT}:8200
    restart: always

#volumes:
  #vhost.d:
  #html:

networks:
  proxy-tier:

secrets:
  nextcloud_admin_user:
    file: ./private/nextcloud_admin_user
  nextcloud_admin_password:
    file: ./private/nextcloud_admin_password
  postgres_db:
    file: ./private/postgres_db
  postgres_user:
    file: ./private/postgres_user
  postgres_password:
    file: ./private/postgres_password
